/***************************************************************************
 *     Copyright (c) 1999-2014, Broadcom Corporation
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 as
 * published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
 *
 * Module Description:
 *                     DO NOT EDIT THIS FILE DIRECTLY
 *
 * This module was generated magically with RDB from a source description
 * file. You must edit the source file for changes to be made to this file.
 *
 *
 * Date:           Generated on              Wed Sep  3 11:52:52 2014
 *                 Full Compile MD5 Checksum 4a20c0e31b928020bbfa96c583b9e661
 *                   (minus title and desc)  
 *                 MD5 Checksum              077c6f684bcabb645ae9da4069fea8e4
 *
 * Compiled with:  RDB Utility               combo_header.pl
 *                 RDB Parser                3.0
 *                 unknown                   unknown
 *                 Perl Interpreter          5.008005
 *                 Operating System          linux
 *
 * Revision History:
 *
 * $brcm_Log: $
 *
 ***************************************************************************/

#ifndef BCHP_GIO_H__
#define BCHP_GIO_H__

/***************************************************************************
 *GIO - GPIO
 ***************************************************************************/
#define BCHP_GIO_ODEN_LO                         0x0040a700 /* GENERAL PURPOSE I/O OPEN DRAIN ENABLE [31:0] */
#define BCHP_GIO_DATA_LO                         0x0040a704 /* GENERAL PURPOSE I/O DATA [31:0] */
#define BCHP_GIO_IODIR_LO                        0x0040a708 /* GENERAL PURPOSE I/O DIRECTION [31:0] */
#define BCHP_GIO_EC_LO                           0x0040a70c /* GENERAL PURPOSE I/O EDGE CONFIGURATION [31:0] */
#define BCHP_GIO_EI_LO                           0x0040a710 /* GENERAL PURPOSE I/O EDGE INSENSITIVE [31:0] */
#define BCHP_GIO_MASK_LO                         0x0040a714 /* GENERAL PURPOSE I/O INTERRUPT MASK [31:0] */
#define BCHP_GIO_LEVEL_LO                        0x0040a718 /* GENERAL PURPOSE I/O INTERRUPT TYPE [31:0] */
#define BCHP_GIO_STAT_LO                         0x0040a71c /* GENERAL PURPOSE I/O INTERRUPT STATUS [31:0] */
#define BCHP_GIO_ODEN_HI                         0x0040a720 /* GENERAL PURPOSE I/O OPEN DRAIN ENABLE [63:32] */
#define BCHP_GIO_DATA_HI                         0x0040a724 /* GENERAL PURPOSE I/O DATA [63:32] */
#define BCHP_GIO_IODIR_HI                        0x0040a728 /* GENERAL PURPOSE I/O DIRECTION [63:32] */
#define BCHP_GIO_EC_HI                           0x0040a72c /* GENERAL PURPOSE I/O EDGE CONFIGURATION [63:32] */
#define BCHP_GIO_EI_HI                           0x0040a730 /* GENERAL PURPOSE I/O EDGE INSENSITIVE [63:32] */
#define BCHP_GIO_MASK_HI                         0x0040a734 /* GENERAL PURPOSE I/O INTERRUPT MASK [63:32] */
#define BCHP_GIO_LEVEL_HI                        0x0040a738 /* GENERAL PURPOSE I/O INTERRUPT TYPE [63:32] */
#define BCHP_GIO_STAT_HI                         0x0040a73c /* GENERAL PURPOSE I/O INTERRUPT STATUS [63:32] */
#define BCHP_GIO_ODEN_EXT                        0x0040a740 /* GENERAL PURPOSE I/O OPEN DRAIN ENABLE [95:64] (GPIO[87:64], AON_SGPIO[1:0], SGPIO[5:0]) */
#define BCHP_GIO_DATA_EXT                        0x0040a744 /* GENERAL PURPOSE I/O DATA [95:64] (GPIO[87:64], AON_SGPIO[1:0], SGPIO[5:0]) */
#define BCHP_GIO_IODIR_EXT                       0x0040a748 /* GENERAL PURPOSE I/O DIRECTION [95:64] (GPIO[87:64], AON_SGPIO[1:0], SGPIO[5:0]) */
#define BCHP_GIO_EC_EXT                          0x0040a74c /* GENERAL PURPOSE I/O EDGE CONFIGURATION [95:64] (GPIO[87:64], AON_SGPIO[1:0], SGPIO[5:0]) */
#define BCHP_GIO_EI_EXT                          0x0040a750 /* GENERAL PURPOSE I/O EDGE INSENSITIVE [95:64] (GPIO[87:64], AON_SGPIO[1:0], SGPIO[5:0]) */
#define BCHP_GIO_MASK_EXT                        0x0040a754 /* GENERAL PURPOSE I/O INTERRUPT MASK [95:64] (GPIO[87:64], AON_SGPIO[1:0], SGPIO[5:0]) */
#define BCHP_GIO_LEVEL_EXT                       0x0040a758 /* GENERAL PURPOSE I/O INTERRUPT TYPE [95:64] (GPIO[87:64], AON_SGPIO[1:0], SGPIO[5:0]) */
#define BCHP_GIO_STAT_EXT                        0x0040a75c /* GENERAL PURPOSE I/O INTERRUPT STATUS [95:64] (GPIO[87:64], AON_SGPIO[1:0], SGPIO[5:0]) */
#define BCHP_GIO_ODEN_EXT_HI                     0x0040a760 /* GENERAL PURPOSE I/O OPEN DRAIN ENABLE [119:96] (GPIO[111:88]) */
#define BCHP_GIO_DATA_EXT_HI                     0x0040a764 /* GENERAL PURPOSE I/O DATA [119:96] (GPIO[111:88]) */
#define BCHP_GIO_IODIR_EXT_HI                    0x0040a768 /* GENERAL PURPOSE I/O DIRECTION [119:96] (GPIO[111:88]) */
#define BCHP_GIO_EC_EXT_HI                       0x0040a76c /* GENERAL PURPOSE I/O EDGE CONFIGURATION [119:96] (GPIO[111:88]) */
#define BCHP_GIO_EI_EXT_HI                       0x0040a770 /* GENERAL PURPOSE I/O EDGE INSENSITIVE [119:96] (GPIO[111:88]) */
#define BCHP_GIO_MASK_EXT_HI                     0x0040a774 /* GENERAL PURPOSE I/O INTERRUPT MASK [119:96] (GPIO[111:88]) */
#define BCHP_GIO_LEVEL_EXT_HI                    0x0040a778 /* GENERAL PURPOSE I/O INTERRUPT TYPE [119:96] (GPIO[111:88]) */
#define BCHP_GIO_STAT_EXT_HI                     0x0040a77c /* GENERAL PURPOSE I/O INTERRUPT STATUS [119:96] (GPIO[111:88]) */

/***************************************************************************
 *ODEN_LO - GENERAL PURPOSE I/O OPEN DRAIN ENABLE [31:0]
 ***************************************************************************/
/* GIO :: ODEN_LO :: oden [31:00] */
#define BCHP_GIO_ODEN_LO_oden_MASK                                 0xffffffff
#define BCHP_GIO_ODEN_LO_oden_SHIFT                                0
#define BCHP_GIO_ODEN_LO_oden_DEFAULT                              0x00000000

/***************************************************************************
 *DATA_LO - GENERAL PURPOSE I/O DATA [31:0]
 ***************************************************************************/
/* GIO :: DATA_LO :: data [31:00] */
#define BCHP_GIO_DATA_LO_data_MASK                                 0xffffffff
#define BCHP_GIO_DATA_LO_data_SHIFT                                0
#define BCHP_GIO_DATA_LO_data_DEFAULT                              0x00000000

/***************************************************************************
 *IODIR_LO - GENERAL PURPOSE I/O DIRECTION [31:0]
 ***************************************************************************/
/* GIO :: IODIR_LO :: iodir [31:00] */
#define BCHP_GIO_IODIR_LO_iodir_MASK                               0xffffffff
#define BCHP_GIO_IODIR_LO_iodir_SHIFT                              0
#define BCHP_GIO_IODIR_LO_iodir_DEFAULT                            0xffffffff

/***************************************************************************
 *EC_LO - GENERAL PURPOSE I/O EDGE CONFIGURATION [31:0]
 ***************************************************************************/
/* GIO :: EC_LO :: edge_config [31:00] */
#define BCHP_GIO_EC_LO_edge_config_MASK                            0xffffffff
#define BCHP_GIO_EC_LO_edge_config_SHIFT                           0
#define BCHP_GIO_EC_LO_edge_config_DEFAULT                         0x00000000

/***************************************************************************
 *EI_LO - GENERAL PURPOSE I/O EDGE INSENSITIVE [31:0]
 ***************************************************************************/
/* GIO :: EI_LO :: edge_insensitive [31:00] */
#define BCHP_GIO_EI_LO_edge_insensitive_MASK                       0xffffffff
#define BCHP_GIO_EI_LO_edge_insensitive_SHIFT                      0
#define BCHP_GIO_EI_LO_edge_insensitive_DEFAULT                    0x00000000

/***************************************************************************
 *MASK_LO - GENERAL PURPOSE I/O INTERRUPT MASK [31:0]
 ***************************************************************************/
/* GIO :: MASK_LO :: irq_mask [31:00] */
#define BCHP_GIO_MASK_LO_irq_mask_MASK                             0xffffffff
#define BCHP_GIO_MASK_LO_irq_mask_SHIFT                            0
#define BCHP_GIO_MASK_LO_irq_mask_DEFAULT                          0x00000000

/***************************************************************************
 *LEVEL_LO - GENERAL PURPOSE I/O INTERRUPT TYPE [31:0]
 ***************************************************************************/
/* GIO :: LEVEL_LO :: level [31:00] */
#define BCHP_GIO_LEVEL_LO_level_MASK                               0xffffffff
#define BCHP_GIO_LEVEL_LO_level_SHIFT                              0
#define BCHP_GIO_LEVEL_LO_level_DEFAULT                            0x00000000

/***************************************************************************
 *STAT_LO - GENERAL PURPOSE I/O INTERRUPT STATUS [31:0]
 ***************************************************************************/
/* GIO :: STAT_LO :: irq_status [31:00] */
#define BCHP_GIO_STAT_LO_irq_status_MASK                           0xffffffff
#define BCHP_GIO_STAT_LO_irq_status_SHIFT                          0
#define BCHP_GIO_STAT_LO_irq_status_DEFAULT                        0x00000000

/***************************************************************************
 *ODEN_HI - GENERAL PURPOSE I/O OPEN DRAIN ENABLE [63:32]
 ***************************************************************************/
/* GIO :: ODEN_HI :: oden [31:00] */
#define BCHP_GIO_ODEN_HI_oden_MASK                                 0xffffffff
#define BCHP_GIO_ODEN_HI_oden_SHIFT                                0
#define BCHP_GIO_ODEN_HI_oden_DEFAULT                              0x00000000

/***************************************************************************
 *DATA_HI - GENERAL PURPOSE I/O DATA [63:32]
 ***************************************************************************/
/* GIO :: DATA_HI :: data [31:00] */
#define BCHP_GIO_DATA_HI_data_MASK                                 0xffffffff
#define BCHP_GIO_DATA_HI_data_SHIFT                                0
#define BCHP_GIO_DATA_HI_data_DEFAULT                              0x00000000

/***************************************************************************
 *IODIR_HI - GENERAL PURPOSE I/O DIRECTION [63:32]
 ***************************************************************************/
/* GIO :: IODIR_HI :: iodir [31:00] */
#define BCHP_GIO_IODIR_HI_iodir_MASK                               0xffffffff
#define BCHP_GIO_IODIR_HI_iodir_SHIFT                              0
#define BCHP_GIO_IODIR_HI_iodir_DEFAULT                            0xffffffff

/***************************************************************************
 *EC_HI - GENERAL PURPOSE I/O EDGE CONFIGURATION [63:32]
 ***************************************************************************/
/* GIO :: EC_HI :: edge_config [31:00] */
#define BCHP_GIO_EC_HI_edge_config_MASK                            0xffffffff
#define BCHP_GIO_EC_HI_edge_config_SHIFT                           0
#define BCHP_GIO_EC_HI_edge_config_DEFAULT                         0x00000000

/***************************************************************************
 *EI_HI - GENERAL PURPOSE I/O EDGE INSENSITIVE [63:32]
 ***************************************************************************/
/* GIO :: EI_HI :: edge_insensitive [31:00] */
#define BCHP_GIO_EI_HI_edge_insensitive_MASK                       0xffffffff
#define BCHP_GIO_EI_HI_edge_insensitive_SHIFT                      0
#define BCHP_GIO_EI_HI_edge_insensitive_DEFAULT                    0x00000000

/***************************************************************************
 *MASK_HI - GENERAL PURPOSE I/O INTERRUPT MASK [63:32]
 ***************************************************************************/
/* GIO :: MASK_HI :: irq_mask [31:00] */
#define BCHP_GIO_MASK_HI_irq_mask_MASK                             0xffffffff
#define BCHP_GIO_MASK_HI_irq_mask_SHIFT                            0
#define BCHP_GIO_MASK_HI_irq_mask_DEFAULT                          0x00000000

/***************************************************************************
 *LEVEL_HI - GENERAL PURPOSE I/O INTERRUPT TYPE [63:32]
 ***************************************************************************/
/* GIO :: LEVEL_HI :: level [31:00] */
#define BCHP_GIO_LEVEL_HI_level_MASK                               0xffffffff
#define BCHP_GIO_LEVEL_HI_level_SHIFT                              0
#define BCHP_GIO_LEVEL_HI_level_DEFAULT                            0x00000000

/***************************************************************************
 *STAT_HI - GENERAL PURPOSE I/O INTERRUPT STATUS [63:32]
 ***************************************************************************/
/* GIO :: STAT_HI :: irq_status [31:00] */
#define BCHP_GIO_STAT_HI_irq_status_MASK                           0xffffffff
#define BCHP_GIO_STAT_HI_irq_status_SHIFT                          0
#define BCHP_GIO_STAT_HI_irq_status_DEFAULT                        0x00000000

/***************************************************************************
 *ODEN_EXT - GENERAL PURPOSE I/O OPEN DRAIN ENABLE [95:64] (GPIO[87:64], AON_SGPIO[1:0], SGPIO[5:0])
 ***************************************************************************/
/* GIO :: ODEN_EXT :: oden [31:00] */
#define BCHP_GIO_ODEN_EXT_oden_MASK                                0xffffffff
#define BCHP_GIO_ODEN_EXT_oden_SHIFT                               0
#define BCHP_GIO_ODEN_EXT_oden_DEFAULT                             0x00000000

/***************************************************************************
 *DATA_EXT - GENERAL PURPOSE I/O DATA [95:64] (GPIO[87:64], AON_SGPIO[1:0], SGPIO[5:0])
 ***************************************************************************/
/* GIO :: DATA_EXT :: data [31:00] */
#define BCHP_GIO_DATA_EXT_data_MASK                                0xffffffff
#define BCHP_GIO_DATA_EXT_data_SHIFT                               0
#define BCHP_GIO_DATA_EXT_data_DEFAULT                             0x00000000

/***************************************************************************
 *IODIR_EXT - GENERAL PURPOSE I/O DIRECTION [95:64] (GPIO[87:64], AON_SGPIO[1:0], SGPIO[5:0])
 ***************************************************************************/
/* GIO :: IODIR_EXT :: iodir [31:00] */
#define BCHP_GIO_IODIR_EXT_iodir_MASK                              0xffffffff
#define BCHP_GIO_IODIR_EXT_iodir_SHIFT                             0
#define BCHP_GIO_IODIR_EXT_iodir_DEFAULT                           0xffffffff

/***************************************************************************
 *EC_EXT - GENERAL PURPOSE I/O EDGE CONFIGURATION [95:64] (GPIO[87:64], AON_SGPIO[1:0], SGPIO[5:0])
 ***************************************************************************/
/* GIO :: EC_EXT :: edge_config [31:00] */
#define BCHP_GIO_EC_EXT_edge_config_MASK                           0xffffffff
#define BCHP_GIO_EC_EXT_edge_config_SHIFT                          0
#define BCHP_GIO_EC_EXT_edge_config_DEFAULT                        0x00000000

/***************************************************************************
 *EI_EXT - GENERAL PURPOSE I/O EDGE INSENSITIVE [95:64] (GPIO[87:64], AON_SGPIO[1:0], SGPIO[5:0])
 ***************************************************************************/
/* GIO :: EI_EXT :: edge_insensitive [31:00] */
#define BCHP_GIO_EI_EXT_edge_insensitive_MASK                      0xffffffff
#define BCHP_GIO_EI_EXT_edge_insensitive_SHIFT                     0
#define BCHP_GIO_EI_EXT_edge_insensitive_DEFAULT                   0x00000000

/***************************************************************************
 *MASK_EXT - GENERAL PURPOSE I/O INTERRUPT MASK [95:64] (GPIO[87:64], AON_SGPIO[1:0], SGPIO[5:0])
 ***************************************************************************/
/* GIO :: MASK_EXT :: irq_mask [31:00] */
#define BCHP_GIO_MASK_EXT_irq_mask_MASK                            0xffffffff
#define BCHP_GIO_MASK_EXT_irq_mask_SHIFT                           0
#define BCHP_GIO_MASK_EXT_irq_mask_DEFAULT                         0x00000000

/***************************************************************************
 *LEVEL_EXT - GENERAL PURPOSE I/O INTERRUPT TYPE [95:64] (GPIO[87:64], AON_SGPIO[1:0], SGPIO[5:0])
 ***************************************************************************/
/* GIO :: LEVEL_EXT :: level [31:00] */
#define BCHP_GIO_LEVEL_EXT_level_MASK                              0xffffffff
#define BCHP_GIO_LEVEL_EXT_level_SHIFT                             0
#define BCHP_GIO_LEVEL_EXT_level_DEFAULT                           0x00000000

/***************************************************************************
 *STAT_EXT - GENERAL PURPOSE I/O INTERRUPT STATUS [95:64] (GPIO[87:64], AON_SGPIO[1:0], SGPIO[5:0])
 ***************************************************************************/
/* GIO :: STAT_EXT :: irq_status [31:00] */
#define BCHP_GIO_STAT_EXT_irq_status_MASK                          0xffffffff
#define BCHP_GIO_STAT_EXT_irq_status_SHIFT                         0
#define BCHP_GIO_STAT_EXT_irq_status_DEFAULT                       0x00000000

/***************************************************************************
 *ODEN_EXT_HI - GENERAL PURPOSE I/O OPEN DRAIN ENABLE [119:96] (GPIO[111:88])
 ***************************************************************************/
/* GIO :: ODEN_EXT_HI :: reserved0 [31:24] */
#define BCHP_GIO_ODEN_EXT_HI_reserved0_MASK                        0xff000000
#define BCHP_GIO_ODEN_EXT_HI_reserved0_SHIFT                       24

/* GIO :: ODEN_EXT_HI :: oden [23:00] */
#define BCHP_GIO_ODEN_EXT_HI_oden_MASK                             0x00ffffff
#define BCHP_GIO_ODEN_EXT_HI_oden_SHIFT                            0
#define BCHP_GIO_ODEN_EXT_HI_oden_DEFAULT                          0x00000000

/***************************************************************************
 *DATA_EXT_HI - GENERAL PURPOSE I/O DATA [119:96] (GPIO[111:88])
 ***************************************************************************/
/* GIO :: DATA_EXT_HI :: reserved0 [31:24] */
#define BCHP_GIO_DATA_EXT_HI_reserved0_MASK                        0xff000000
#define BCHP_GIO_DATA_EXT_HI_reserved0_SHIFT                       24

/* GIO :: DATA_EXT_HI :: data [23:00] */
#define BCHP_GIO_DATA_EXT_HI_data_MASK                             0x00ffffff
#define BCHP_GIO_DATA_EXT_HI_data_SHIFT                            0
#define BCHP_GIO_DATA_EXT_HI_data_DEFAULT                          0x00000000

/***************************************************************************
 *IODIR_EXT_HI - GENERAL PURPOSE I/O DIRECTION [119:96] (GPIO[111:88])
 ***************************************************************************/
/* GIO :: IODIR_EXT_HI :: reserved0 [31:24] */
#define BCHP_GIO_IODIR_EXT_HI_reserved0_MASK                       0xff000000
#define BCHP_GIO_IODIR_EXT_HI_reserved0_SHIFT                      24

/* GIO :: IODIR_EXT_HI :: iodir [23:00] */
#define BCHP_GIO_IODIR_EXT_HI_iodir_MASK                           0x00ffffff
#define BCHP_GIO_IODIR_EXT_HI_iodir_SHIFT                          0
#define BCHP_GIO_IODIR_EXT_HI_iodir_DEFAULT                        0x00ffffff

/***************************************************************************
 *EC_EXT_HI - GENERAL PURPOSE I/O EDGE CONFIGURATION [119:96] (GPIO[111:88])
 ***************************************************************************/
/* GIO :: EC_EXT_HI :: reserved0 [31:24] */
#define BCHP_GIO_EC_EXT_HI_reserved0_MASK                          0xff000000
#define BCHP_GIO_EC_EXT_HI_reserved0_SHIFT                         24

/* GIO :: EC_EXT_HI :: edge_config [23:00] */
#define BCHP_GIO_EC_EXT_HI_edge_config_MASK                        0x00ffffff
#define BCHP_GIO_EC_EXT_HI_edge_config_SHIFT                       0
#define BCHP_GIO_EC_EXT_HI_edge_config_DEFAULT                     0x00000000

/***************************************************************************
 *EI_EXT_HI - GENERAL PURPOSE I/O EDGE INSENSITIVE [119:96] (GPIO[111:88])
 ***************************************************************************/
/* GIO :: EI_EXT_HI :: reserved0 [31:24] */
#define BCHP_GIO_EI_EXT_HI_reserved0_MASK                          0xff000000
#define BCHP_GIO_EI_EXT_HI_reserved0_SHIFT                         24

/* GIO :: EI_EXT_HI :: edge_insensitive [23:00] */
#define BCHP_GIO_EI_EXT_HI_edge_insensitive_MASK                   0x00ffffff
#define BCHP_GIO_EI_EXT_HI_edge_insensitive_SHIFT                  0
#define BCHP_GIO_EI_EXT_HI_edge_insensitive_DEFAULT                0x00000000

/***************************************************************************
 *MASK_EXT_HI - GENERAL PURPOSE I/O INTERRUPT MASK [119:96] (GPIO[111:88])
 ***************************************************************************/
/* GIO :: MASK_EXT_HI :: reserved0 [31:24] */
#define BCHP_GIO_MASK_EXT_HI_reserved0_MASK                        0xff000000
#define BCHP_GIO_MASK_EXT_HI_reserved0_SHIFT                       24

/* GIO :: MASK_EXT_HI :: irq_mask [23:00] */
#define BCHP_GIO_MASK_EXT_HI_irq_mask_MASK                         0x00ffffff
#define BCHP_GIO_MASK_EXT_HI_irq_mask_SHIFT                        0
#define BCHP_GIO_MASK_EXT_HI_irq_mask_DEFAULT                      0x00000000

/***************************************************************************
 *LEVEL_EXT_HI - GENERAL PURPOSE I/O INTERRUPT TYPE [119:96] (GPIO[111:88])
 ***************************************************************************/
/* GIO :: LEVEL_EXT_HI :: reserved0 [31:24] */
#define BCHP_GIO_LEVEL_EXT_HI_reserved0_MASK                       0xff000000
#define BCHP_GIO_LEVEL_EXT_HI_reserved0_SHIFT                      24

/* GIO :: LEVEL_EXT_HI :: level [23:00] */
#define BCHP_GIO_LEVEL_EXT_HI_level_MASK                           0x00ffffff
#define BCHP_GIO_LEVEL_EXT_HI_level_SHIFT                          0
#define BCHP_GIO_LEVEL_EXT_HI_level_DEFAULT                        0x00000000

/***************************************************************************
 *STAT_EXT_HI - GENERAL PURPOSE I/O INTERRUPT STATUS [119:96] (GPIO[111:88])
 ***************************************************************************/
/* GIO :: STAT_EXT_HI :: reserved0 [31:24] */
#define BCHP_GIO_STAT_EXT_HI_reserved0_MASK                        0xff000000
#define BCHP_GIO_STAT_EXT_HI_reserved0_SHIFT                       24

/* GIO :: STAT_EXT_HI :: irq_status [23:00] */
#define BCHP_GIO_STAT_EXT_HI_irq_status_MASK                       0x00ffffff
#define BCHP_GIO_STAT_EXT_HI_irq_status_SHIFT                      0
#define BCHP_GIO_STAT_EXT_HI_irq_status_DEFAULT                    0x00000000

#endif /* #ifndef BCHP_GIO_H__ */

/* End of File */
